# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decide < Formula
  desc "Ask typed questions about your data and get answers with probabilities"
  homepage "https://github.com/deepnoodle-ai/decide"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deepnoodle-ai/decide/releases/download/v0.2.1/decide_darwin_amd64.tar.gz"
      sha256 "32070d9b6d5875e4d09ac387c25aa419d57089b25bf888d3343994c124fa81ec"

      define_method(:install) do
        bin.install "decide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deepnoodle-ai/decide/releases/download/v0.2.1/decide_darwin_arm64.tar.gz"
      sha256 "848f30ea9f761c106a9efb085217055b8f41fb5d109eababc0beaf4daa6270ba"

      define_method(:install) do
        bin.install "decide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepnoodle-ai/decide/releases/download/v0.2.1/decide_linux_amd64.tar.gz"
      sha256 "0c096b15a3d167a649ab399b9fce9834a076174b5d363b6ced26dc9fccd34894"
      define_method(:install) do
        bin.install "decide"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepnoodle-ai/decide/releases/download/v0.2.1/decide_linux_arm64.tar.gz"
      sha256 "0f1a3639e8c734e02e4a4ad4812bf28aa1059871ce147f4e4f62b58b4148593e"
      define_method(:install) do
        bin.install "decide"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/decide --version")
  end
end
