# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Decide < Formula
  desc "Ask typed questions about your data and get answers with probabilities"
  homepage "https://github.com/deepnoodle-ai/decide"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deepnoodle-ai/decide/releases/download/v0.1.0/decide_darwin_amd64.tar.gz"
      sha256 "2e382357e8e3a706f886e862ec0b0775a4c17d70ba611e31cc036ec69712bd1b"

      define_method(:install) do
        bin.install "decide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deepnoodle-ai/decide/releases/download/v0.1.0/decide_darwin_arm64.tar.gz"
      sha256 "8ac41addd2926f0f5cbaefb9301996bfa7cf5d994e7731c2283f0558a42328b8"

      define_method(:install) do
        bin.install "decide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepnoodle-ai/decide/releases/download/v0.1.0/decide_linux_amd64.tar.gz"
      sha256 "e677ec30329d6d97c175f268578cefe493502f48ca5963f8ea557ed68048441c"
      define_method(:install) do
        bin.install "decide"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepnoodle-ai/decide/releases/download/v0.1.0/decide_linux_arm64.tar.gz"
      sha256 "d089a2d51660de6e127f5c1b54ea521c1e62be32332f47acd75e2467ecff629a"
      define_method(:install) do
        bin.install "decide"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/decide --version")
  end
end
